bank/api/v1/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views as auth_views

from bank.api.v1 import views

router = routers.DefaultRouter()
router.register(r'account', views.AccountViewSet, basename='Account')
router.register(r'corporation', views.CorporationViewSet, basename='Corporation')
router.register(r'featured_corporation', views.FeaturedCorporationViewSet, basename='FeaturedCorporation')
router.register(r'transaction', views.TransactionViewSet, basename='Transaction')
router.register(r'user', views.UserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('accounts/<int:discord_id>/', views.AccountsPerDiscordUser.as_view()),
    path('discord_user/<int:discord_id>/', views.UserAccountFromDiscordUser.as_view()),
    path('send/', views.TransactionCreate.as_view()),
    path('statistics/', views.BankStatistics.as_view()),
    path('default_account/', views.DefaultBankAccount.as_view()),
    path('ottoman/apply/', views.ApplyOttomanFormula.as_view()),
    path('ottoman/threshold/', views.OttomanThresholds.as_view()),
    path('currencies/', views.CurrenciesView.as_view()),
    path('token/', auth_views.obtain_auth_token),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

bank/urls.py
from django.urls import path

from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.index, name='index'),
    path('me/', views.UserProfileView.as_view(), name='user'),
    path('me/employment/', views.UserEmploymentOverviewView.as_view(), name='user-employment'),
    path('me/leave_organization/<int:employee>/',
         views.LeaveCorporationView.as_view(), name='user-employee-leave'),
    path('me/discord/', views.discord_connect,
         name='user-discord-connect'),
    path('me/invite/<int:pk>/<str:action>/', views.EmployeeInviteView.as_view(),
         name='user-employee-invite'),
    path('account/', views.AccountListView.as_view(), name='account'),
    path('account/new/', views.account_creation_chooser,
         name='account-create'),
    path('account/new/personal/', views.PersonalAccountCreateView.as_view(),
         name='account-create-personal'),
    path('account/new/corporate/', views.CorporateAccountCreateView.as_view(),
         name='account-create-corporate'),
    path('account/<uuid:pk>/', views.AccountDetailView.as_view(),
         name='account-detail'),
    path('account/<uuid:pk>/edit/', views.AccountUpdateView.as_view(),
         name='account-update'),
    path('account/<uuid:pk>/delete/',
         views.AccountDeleteView.as_view(), name='account-delete'),
    path('transaction/new/', views.TransactionCreateView.as_view(),
         name='account-transaction-create'),
    path('transaction/confirm/', views.TransactionConfirmView.as_view(),
         name='account-transaction-confirm'),
    path('transaction/<uuid:pk>/', views.TransactionDetailView.as_view(),
         name='account-transaction-detail'),
    path('organization/', views.CorporationListView.as_view(),
         name='corporation-list'),
    path('organization/new/', views.CorporationCreateView.as_view(),
         name='corporation-create'),
    path('organization/<str:pk>/', views.CorporationDetailView.as_view(),
         name='corporation-detail'),
    path('organization/<str:pk>/delete/',
         views.CorporationDeleteView.as_view(), name='corporation-delete'),
    path('organization/<str:pk>/edit/',
         views.CorporateUpdateView.as_view(), name='corporation-update'),
    path('organization/<str:pk>/employees/',
         views.ManageEmployeeView.as_view(), name='corporation-employees'),
    path('organization/<str:pk>/employees/fire/<int:employee>/',
         views.FireEmployeeView.as_view(), name='corporation-employees-fire'),
    path('organization/<str:pk>/employees/transfer/<int:employee>/',
         views.TransferOwnershipView.as_view(), name='corporation-employees-transfer-ownership'),
    path('marketplace/', views.MarketplaceView.as_view(), name='marketplace'),
    path('discord/', views.discord_callback, name='user-discord-callback'),
    path('u/<int:discord_id>', views.bot_resubmit_view, name='bot-resubmit')
]

democraciv_web/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from bank import views as bank_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('bank.urls', namespace='bank')),
    path('register/', bank_views.RegisterView.as_view(template_name='bank/register.html'), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='bank/login.html', extra_context=bank_views.make_context()), name='login'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='bank/change_password.html', extra_context=bank_views.make_context(), success_url=reverse_lazy('bank:user')), name="change-password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='bank/logout.html', extra_context=bank_views.make_context()), name='logout'),
    path('reset-password/', bank_views.PasswordResetViewNoEmail.as_view(template_name="bank/password_reset.html"), name="password_reset"),
    path('reset-password/sent', auth_views.PasswordResetDoneView.as_view(template_name="bank/password_reset_sent.html", extra_context=bank_views.make_context()), name="password_reset_done"),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="bank/password_reset_confirm.html", extra_context=bank_views.make_context()), name="password_reset_confirm"),
    path('reset-password/done', auth_views.PasswordResetCompleteView.as_view(template_name="bank/password_reset_done.html", extra_context=bank_views.make_context()), name="password_reset_complete"),
    path('admin/', admin.site.urls),
    path('twitch/callback', bank_views.bot_twitch_callback),
    path('api/v1/', include('bank.api.v1.urls')),
]

bank/models.py
import uuid
import moneyed
import django_tables2 as tables

from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.db import models, transaction
from django.utils.html import format_html
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import CICharField

from djmoney.models import fields


class User(AbstractUser):
    # first_time_login = models.BooleanField(default=True)
    discord_id = models.BigIntegerField(null=True, unique=True)
    discord_profile_picture_url = models.URLField(null=True)
    discord_username = models.CharField(max_length=50, null=True)
    discord_dms_enabled = models.BooleanField(
        default=True, verbose_name="Notifications via the Democraciv Discord Bot")


class Corporation(models.Model):
    name = models.CharField(unique=True, max_length=100)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    abbreviation = CICharField(primary_key=True, max_length=8,
                               help_text="You cannot change the abbreviation in the future.")
    created_on = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=1000)
    discord_server = models.CharField(
        null=True, blank=True, max_length=50, help_text="You can leave this blank.")
    is_public_viewable = models.BooleanField(default=True)

    class Meta:
        permissions = (
            ('manage_employees', 'Invite new people and fire existing employees'),
            ('add_corp_account', 'Create corporate bank account'),
        )

    class Nations(models.TextChoices):
        JAPAN = "JP", "Japan"

    nation = models.CharField(
        max_length=2,
        choices=Nations.choices,
        default=Nations.JAPAN,
        help_text="Select the nation you operate out of. Different nations may have different laws on "
                  "things like corporate tax.")

    class OrganizationTypes(models.TextChoices):
        CORPORATION = "CORP", "Corporation"
        ORGANIZATION = "ORG", "Organization"
        GOVERNMENT = "GOV", "Government Entity"
        NON_PROFIT = "NPO", "Non-Profit"
        SPECIAL_INTEREST = "SIG", "Special Interest Group"

    organization_type = models.CharField(
        max_length=4,
        choices=OrganizationTypes.choices,
        default=OrganizationTypes.CORPORATION,
        help_text="This is purely for role-playing purposes and has no effect on anything.",
        verbose_name="Type of Organization"
    )

    class Industries(models.TextChoices):
        AD = "AD", "Advertisement & Campaign Services"
        FINANCE = "F", "Financial Services"
        PRESS = "PR", "Press"
        DEFENSE = "D", "Defense"
        OTHER = "O", "Other"

    industry = models.CharField(
        max_length=2,
        choices=Industries.choices,
        null=True,
        blank=True,
        help_text="This is purely for role-playing purposes and has no effect on anything. You can leave this blank.")

    def __str__(self):
        return self.name

    def get_discord_ids(self):
        employees = self.employee_set.all()
        ids = [employee.person.discord_id for employee in employees
               if employee.person.discord_id and employee.person.discord_dms_enabled]

        if self.owner.discord_id and self.owner.discord_dms_enabled:
            ids.append(self.owner.discord_id)

        return ids

    def get_absolute_url(self):
        return reverse('bank:corporation-detail', kwargs={'pk': self.abbreviation})


class FeaturedCorporation(models.Model):
    corporation = models.OneToOneField(Corporation, on_delete=models.CASCADE)
    featured_since = models.DateTimeField(default=timezone.now)
    ad_message = models.TextField(max_length=1000)

    def __str__(self):
        return self.corporation.name


class Employee(models.Model):
    person = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="employed_at")
    corporation = models.ForeignKey(Corporation, on_delete=models.CASCADE)
    employed_since = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('person', 'corporation',)

    def __str__(self):
        return f"{self.person.username} ({self.corporation.abbreviation})"


class EmployeeInvitation(models.Model):
    potential_employee = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    corporation = models.ForeignKey(Corporation, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('potential_employee', 'corporation',)

    def __str__(self):
        return f"{self.potential_employee.username} ({self.corporation.abbreviation})"


class Account(models.Model):
    iban = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(
        max_length=100, editable=True, default='Bank Account')
    balance = fields.MoneyField(max_digits=20, decimal_places=2,
                                default_currency='USD', default=0)
    currency = fields.CurrencyField()

    is_frozen = models.BooleanField(default=False)
    is_default_for_currency = models.BooleanField(verbose_name="Default Bank Account for this Currency",
                                                  default=True,
                                                  help_text="This bank account will be used when someone tries to "
                                                            "send you money in this currency without specifying an "
                                                            "IBAN, for example with the Democraciv Discord Bot. "
                                                            "You can only have one default bank account per currency.")
    created_on = models.DateTimeField(default=timezone.now)

    individual_holder = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    corporate_holder = models.ForeignKey(
        Corporation, null=True, blank=True, on_delete=models.SET_NULL)

    ottoman_threshold_variable = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    is_reserve = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def clean(self):
        # Don't allow both a Corporation and a User to own this Account
        if self.corporate_holder and self.individual_holder:
            raise ValidationError(
                'A bank account can have either an Individual holder or a Corporate holder, not both.')

        self.balance.currency = moneyed.Currency(code=self.currency)
        self.balance_currency = self.currency

    def get_absolute_url(self):
        return reverse('bank:account-detail', kwargs={'pk': self.pk})

    @property
    def holder(self):
        return self.individual_holder if self.individual_holder else self.corporate_holder

    @property
    def owner(self):
        if self.individual_holder:
            return self.individual_holder
        elif self.corporate_holder:
            return self.corporate_holder.owner

    @property
    def pretty_holder(self):
        return str(self.holder)

    def get_discord_ids(self):
        if self.individual_holder:
            if not self.individual_holder.discord_id or not self.individual_holder.discord_dms_enabled:
                return []

            return [self.individual_holder.discord_id]

        elif self.corporate_holder:
            return self.corporate_holder.get_discord_ids()


def get_deleted_account():
    return Account.objects.get_or_create(iban=uuid.UUID('00000000-0000-0000-0000-000000000000'),
                                         name="Deleted Bank Account",
                                         is_frozen=True)[0]


class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    from_account = models.ForeignKey(Account, on_delete=models.SET(
        get_deleted_account), related_name='transactions_from')
    to_account = models.ForeignKey(Account, on_delete=models.SET(
        get_deleted_account), related_name='transactions_to')
    amount = fields.MoneyField(max_digits=20, decimal_places=2)
    purpose = models.TextField(max_length=500, blank=True, default="", help_text="The recipient can read this. You can "
                                                                                 "leave this blank.")
    created_on = models.DateTimeField(default=timezone.now)

    authorized_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                      on_delete=models.SET_NULL,
                                      null=True)

    class TransactionState(models.TextChoices):
        SUCCESSFUL = 'SC', 'Successful'
        REVOKED = 'RV', 'Revoked'

    state = models.CharField(
        max_length=2,
        choices=TransactionState.choices,
        default=TransactionState.SUCCESSFUL,
    )

    def __str__(self):
        return str(self.id)

    def clean(self):
        try:
            if self.from_account == self.to_account:
                raise ValidationError(
                    "You cannot send money to the same bank account you're sending from.")
        except Transaction.to_account.RelatedObjectDoesNotExist:
            return

        if self.from_account.balance.currency != self.to_account.balance.currency:
            raise ValidationError(
                "You cannot send money to a bank account that has a different currency.")

        self.amount.currency = self.from_account.balance.currency
        self.amount_currency = self.amount.currency.code

        if self.amount > self.from_account.balance:
            raise ValidationError(
                'You have insufficient funds in your bank account.')

        if self.to_account.is_frozen:

bank/templates/bank/account_create.html
{% extends "bank/base.html" %}
{% block body %}
    <div class="content-section">
       <h5 class="border-bottom md-1">Personal Bank Account</h5>
        <p class="text-muted">You are the only one with access to your personal bank accounts.</p>
        <a href="{% url 'bank:account-create-personal'%}"><button class="btn btn-primary" style="margin-bottom: 10px" ><i class="fas fa-user"></i>  Open a new Personal Bank Account</button></a>
        <br><br>
        <h5 class="border-bottom md-1">Shared Bank Account</h5>
        <p class="text-muted">Every employee in an organization has access to all of its bank accounts.</p>
        <a href="{% url 'bank:account-create-corporate'%}"><button class="btn btn-primary" style="margin-bottom: 10px"><i class="fas fa-users"></i>  Open a new Bank Account for one of your organizations</button></a>
    </div>

{% endblock body %}

bank/templates/bank/account_list.html
{% extends "bank/base.html" %}
{% load render_table from django_tables2 %}
{% block body %}

    <div class="content-section">
        <h2 class="border-bottom md-2">Bank Accounts</h2>
        <h6 class="text-muted">You can see every bank account you have access to here, both your personal ones and bank accounts from organizations that you're part of.</h6>
        <br>
        <a href="{% url 'bank:account-create'%}"><button class="btn btn-success"><i class="fas fa-plus fa-sm"></i>   Open a new Bank Account</button></a>
        <br>
        <br>
        <div class="table-responsive">
            {% render_table table %}
        </div>
    </div>

{% endblock body %}

bank/templates/bank/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
        <title>{{ title }} | {{ bank_name }}</title>
        <meta property="og:title" content="{{ title }} | {{ bank_name }}"/>
    {% elif not title and bank_name %}
        <title>{{ bank_name }}</title>
        <meta property="og:title" content="{{ bank_name }}"/>
    {% endif %}

    {% if not bank_name and not title %}
        <title>Bank of Democraciv</title>
    {% endif %}

    <link rel="shortcut icon" href="{%  static 'bank/favicon.ico' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Bank Platform built with Django">
    <meta name="keywords" content="">

    {% if not description %}
        <meta property="og:description" content="Open unlimited personal & shared bank accounts and send money in multiple currencies across nations">
    {% else %}
        <meta property="og:description" content="{{ description }}">
    {% endif %}
    <meta property="og:type" content="website">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'bank/main.css' %}">
    <script src="https://kit.fontawesome.com/f17838b2e6.js" crossorigin="anonymous"></script>

</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        {% if bank_name %}
            <a class="navbar-brand" href="{% url 'bank:index' %}">{{ bank_name }}  <span class="badge badge-dark">Beta</span></a>
        {% else %}
            <a class="navbar-brand" href="{% url 'bank:index' %}">Bank of Democraciv  <span class="badge badge-dark">Beta</span></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'bank:account-transaction-create' %}">
                <i class="fas fa-paper-plane"></i>
                  Send Money
            </a>
          </div>

          <div class="navbar-nav" >
            <a class="nav-item nav-link" href="{% url 'bank:account' %}">
                <i class="fas fa-coins"></i>
                  Bank Accounts
            </a>
          </div>

          <!-- First dropdown -->
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-university"></i>
                  Organizations
              </a>
                <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown1">
                  <a class="dropdown-item" href="{% url 'bank:corporation-list' %}">My organizations</a>
                  <a class="dropdown-item" href="{% url 'bank:corporation-create' %}">Form a new organization</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'bank:marketplace' %}">Marketplace</a>
                </div>
            </li>
          </ul>

          <!-- Second dropdown -->
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {% if user.is_authenticated  %}
                  <i class="fas fa-user-circle"></i>
                   {{ user.username }}
               {% else %}
                  <i class="fas fa-user-circle"></i>
                   Login
               {% endif %}
              </a>
                <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown2">
                  {% if user.is_authenticated  %}
                    <a class="dropdown-item" href="{% url 'bank:user-employment' %}">Employment</a>
                    <a class="dropdown-item" href="{% url 'bank:user' %}">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                  {% endif %}
                </div>
            </li>
          </ul>

        </div>
      </div>
    </nav>
  </header>

  <main role="main" class="container">
    <div class="row">
      <div class="col">
          {% if messages %}
              {% for message in messages %}
                  {% if message.tags == 'error' %}
                    <div class="alert alert-danger">
                      {{ message }}
                    </div>
                  {% else %}
                    <div class="alert alert-{{ message.tags }}">
                      {{ message }}
                    </div>
                  {% endif %}
              {% endfor %}
        {% endif %}
        {% block body %}
        {% endblock %}
          <!-- Footer -->
          <footer class="py-5">
            <div class="container text-center">
              <br><br>
              <p class="m-0">Copyright &copy; Jonas Bohmann 2020-2021</p>
              <p class="m-0 text-muted">This is not a real bank, and there is no real money involved here. We're part of a role-playing community where we simulate politics, laws, nations, political parties, and an economy.</p>
            </div>
          </footer>
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

bank/templates/bank/change_password.html
{% extends "bank/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change your Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Confirm</button>
            </div>
        </form>
    </div>
{% endblock body %}

bank/templates/bank/corporation_confirm_transfer_ownership.html
{% extends "bank/base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="content-section">
      <h2>Are you sure?</h2>
      <p class="text-muted">This will make {{ new_owner }} the new owner of {{ org }}, and you will become an employee.</p>
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-danger" type="submit">Yes, I am sure</button>
        </div>
      </form>
    </div>
{% endblock body %}

bank/templates/bank/corporation_detail.html
{% extends "bank/base.html" %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block body %}
    <div class="container">
        <div class="content-section">
            <div class="row align-items-start">
                <div class="col col-9">
                    <h2 class="border-bottom md-2">{{ corporation.name }}</h2>
                    <p class="lead">{{ corporation.get_organization_type_display }} from {{ corporation.get_nation_display }}</p>
                    <h6 class="font-weight-bold">Abbreviation</h6><p>{{ corporation.abbreviation }}</p>

                    {% if corporation.industry %}
                        <h6 class="font-weight-bold">Industry</h6><p>{{ corporation.get_industry_display }}</p>
                    {% endif %}

                    {% if corporation.discord_server %}
                        <h6 class="font-weight-bold">Discord Server </h6><a href="{{ corporation.discord_server }}"><p><i class="fab fa-discord"></i>   Join</p></a>
                    {% endif %}

                    <h6 class="font-weight-bold">Founded on</h6><p>{{ corporation.created_on|date:"F d, Y \U\T\C"  }}</p>
                    <h6 class="font-weight-bold">Description</h6><p>{{ corporation.description|linebreaks }}</p>
                </div>

                {% if is_employed %}
                    <div class="col align-self-end">
                        <div class="card" style="width: fit-content">
                          <div class="card-body">
                            <h5 class="card-title">Actions</h5>
                            <a href="{% url 'bank:corporation-employees' corporation.pk %}"><button class="btn btn-primary" style="margin-bottom: 10px"><i class="fas fa-users"></i>  Employees</button></a>
                            <a href="{% url 'bank:corporation-update' corporation.pk %}"><button class="btn btn-warning" style="margin-bottom: 10px"><i class="fas fa-edit"></i>  Edit</button></a>
                            {% if is_boss %}
                              <a href="{% url 'bank:corporation-delete' corporation.pk %}"><button class="btn btn-danger" style="margin-bottom: 10px"><i class="fas fa-trash"></i>  Delete</button></a>
                            {% endif %}
                          </div>
                        </div>
                    </div>
                {% endif %}
            </div>

            {% if is_employed and table %}
            <div class="row mt-5">
                <div class="col">
                    <h4>Bank Accounts</h4>
                        <div class="table-responsive">
                            {% render_table table %}
                        </div>
                </div>
            </div>
            {% endif %}

        </div>
    </div>

{% endblock body %}

bank/templates/bank/marketplace.html
{% extends "bank/base.html" %}
{% block body %}

    <div class="content-section">
        <h2 class="border-bottom md-2">The Marketplace</h2>
        <h6 class="text-muted">Explore organizations and corporations from every nation around the globe. Not every organization is listed here, since every organization has to opt-in to be on the Marketplace.</h6>
        <br>

        {% for f_corporation in featured %}
            <p class="h5 text-danger mb-6"><a href="{% url 'bank:corporation-detail' f_corporation.corporation.abbreviation %}"><span class="badge badge-warning">Ad</span>  {{ f_corporation.corporation.name }}</a></p>
            <p>{{ f_corporation.ad_message|linebreaks }}</p>
        {% endfor %}

    </div>

    <div class="row row-cols-1 row-cols-md-2">

    {% for corporation in corporations %}
      <div class="col mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title">{{ corporation.name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ corporation.get_organization_type_display }} from {{ corporation.get_nation_display }}</h6>
              <p class="card-text">{{ corporation.description|linebreaks }}</p>
            </div>
              <div class="card-footer">
                <a href="{% url 'bank:corporation-detail' corporation.abbreviation %}" class="card-link">Details</a>
                {% if corporation.discord_server %}
                <a href="{{ corporation.discord_server }}" class="card-link"><i class="fab fa-discord"></i>   Discord Server</a>
                {% endif %}
              </div>
          </div>
      </div>
    {% endfor %}

    </div>

{% endblock body %}

bank/templates/bank/user_employment.html
{% extends "bank/base.html" %}
{% block body %}

<div class="content-section">
    <h3 class="border-bottom md-2">Employment Overview</h3>
    <p class="text-muted">You can be an employee of as many organization as you wish. The owner of an organization
        can invite you to join them, and you can accept or decline their invitation here.</p>


    <h5>Current Employment</h5>
    {% if employed_corps %}
        <ul class="list-group">
          {% for employee_status in employed_corps %}
              <li class="list-group-item">{{ employee_status.corporation.name }} (since {{ employee_status.employed_since|date:"F d, Y" }})<a href="{% url 'bank:user-employee-leave' employee_status.pk %}"><button class="btn btn-danger btn-sm" style="margin-left: 1em" >Leave</button></a></li>
          {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">You're not employed anywhere.</p>
    {% endif %}

    <br>
    {% if invites %}
    <h5>Pending Employment Invitations</h5>
    <ul class="list-group">
        {% for invite in invites %}
            <li class="list-group-item">{{ invite.corporation.name }}<a href="{% url 'bank:user-employee-invite' invite.pk 'accept' %}"><button class="btn btn-success btn-sm" style="margin-left: 1em" >Accept</button></a><a href="{% url 'bank:user-employee-invite' invite.pk 'reject'%}"><button class="btn btn-danger btn-sm" style="margin-left: 1em">Decline</button></a></li>
        {% endfor %}
        <br><br>
    </ul>
    {% endif %}
    <br>
</div>
{% endblock body %}